# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('aadhar', models.CharField(max_length=100, unique=True)),
                ('cid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('aadhar', models.CharField(max_length=100, unique=True)),
                ('vid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionmgmt.Voter'),
        ),
    ]
